.TH COMCAST 8 "28 Jan 2015" "1.0" "comcast 1.0"
.SH NAME
comcast \- The worlds best Go app
.SH SYNOPSIS
comcast [ARGS]
.SH DESCRIPTION
comcast is the worlds best Go app.
.SH OPTIONS
comcast is the worlds best Go app.
.SH SEE ALSO
xfinity(8)
.SH BUGS
comcast is the worlds best Go app. There are no bugs.
.SH AUTHOR
Asshole Brown
